In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer

In [2]:
train = pd.read_csv('./word2vec-nlp-tutorial/labeledTrainData.tsv', header=0, delimiter='\t', quoting=3)
test = pd.read_csv('./word2vec-nlp-tutorial/testData.tsv', header=0, delimiter='\t', quoting=3)
unlabeled_train = pd.read_csv('./word2vec-nlp-tutorial/unlabeledTrainData.tsv', header=0, delimiter='\t', quoting=3)

print ("Read %d labeled train reviews, %d labeled test reviews, " \
 "and %d unlabeled reviews\n" % (train["review"].size,  
 test["review"].size, unlabeled_train["review"].size ))

lemmatizer = WordNetLemmatizer()

Read 25000 labeled train reviews, 25000 labeled test reviews, and 50000 unlabeled reviews



In [3]:
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Lemmatizer
    #words = [lemmatizer.lemmatize(token, "v") for token in words]
    
    # 5. Return a list of words
    return(words)

In [4]:
# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download()   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Define a function to split a review into parsed sentences
def review_to_sentences( review, tokenizer, remove_stopwords=False ):
    # Function to split a review into parsed sentences. Returns a 
    # list of sentences, where each sentence is a list of words
    #
    # 1. Use the NLTK tokenizer to split the paragraph into sentences
    raw_sentences = tokenizer.tokenize(review.strip())
    #
    # 2. Loop over each sentence
    sentences = []
    for raw_sentence in raw_sentences:
        # If a sentence is empty, skip it
        if len(raw_sentence) > 0:
            # Otherwise, call review_to_wordlist to get a list of words
            sentences.append( review_to_wordlist( raw_sentence, \
              remove_stopwords ))
    #
    # Return the list of sentences (each sentence is a list of words,
    # so this returns a list of lists
    return sentences

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [5]:
sentences = []  # Initialize an empty list of sentences

print ("Parsing sentences from training set")
for review in train["review"]:
    sentences += review_to_sentences(review, tokenizer)

print ("Parsing sentences from unlabeled set")
for review in unlabeled_train["review"]:
    sentences += review_to_sentences(review, tokenizer)

Parsing sentences from training set


D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'.'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.happierabroad.com"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup


Parsing sentences from unlabeled set


D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.archive.org/details/LovefromaStranger"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.loosechangeguide.com/LooseChangeGuide.html"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
D:\Anaconda3\envs\virenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'... ...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
D:\Anaconda3\envs

In [9]:
print(len(sentences))

795538


In [10]:
print(sentences[1])

['maybe', 'i', 'just', 'want', 'to', 'get', 'a', 'certain', 'insight', 'into', 'this', 'guy', 'who', 'i', 'thought', 'was', 'really', 'cool', 'in', 'the', 'eighties', 'just', 'to', 'maybe', 'make', 'up', 'my', 'mind', 'whether', 'he', 'is', 'guilty', 'or', 'innocent']


In [11]:
word_set = set([])
word_dict = dict()
i = 0
for sentence in sentences:
    for word in sentence:
        if not word in word_dict:
            word_dict[word] = 1
        else:
            word_dict[word] = word_dict[word] + 1
    
    i+=1
    if i==1000:
        print(i)
        print(len(word_dict))

1000
4549


In [12]:
print(word_dict)
print(len(word_dict))

{'pizzle': 2, 'pota': 15, 'rez': 14, 'falak': 1, 'crest': 18, 'computers': 202, 'cagneyesque': 1, 'auscrit': 3, 'state': 1628, 'radler': 2, 'crudeness': 16, 'precious': 365, 'underplotted': 1, 'guacamole': 3, 'tch': 41, 'dore': 4, 'giraldi': 2, 'fun': 8110, 'wormholes': 10, 'molla': 5, 'feted': 4, 'unquiet': 2, 'worshippers': 23, 'wormface': 1, 'durations': 1, 'glue': 59, 'werching': 1, 'reticent': 9, 'lingers': 73, 'scripii': 1, 'laurentiis': 5, 'uncinematic': 7, 'technially': 1, 'reeve': 148, 'oooh': 31, 'reinstall': 1, 'broken': 892, 'gameshows': 2, 'assists': 24, 'allwyn': 2, 'suppositions': 2, 'paquet': 1, 'contemplates': 10, 'floozy': 19, 'nooooooooooooo': 3, 'niche': 85, 'saddens': 22, 'larch': 1, 'alp': 2, 'cold': 1662, 'ammo': 41, 'furrier': 4, 'composites': 4, 'timeshifts': 1, 'nippons': 1, 'achille': 1, 'plasticized': 3, 'corals': 2, 'reapplies': 1, 'proctology': 3, 'forestalling': 1, 'kelleman': 2, 'dooblebop': 1, 'jl': 1, 'killingtons': 1, 'ooooof': 1, 'poisoner': 3, 'turm

In [13]:
important_words = []
for word in word_dict.keys():
    if word_dict[word]>40:
        important_words.append(word)

In [14]:
print(important_words)
print(len(important_words))

['computers', 'state', 'precious', 'tch', 'fun', 'glue', 'lingers', 'reeve', 'broken', 'niche', 'cold', 'ammo', 'turmoil', 'montreal', 'the', 'clerks', 'behavior', 'allegedly', 'frye', 'passage', 'billed', 'drunks', 'avid', 'concentration', 'sisters', 'ramblings', 'delightful', 'muni', 'indifference', 'perpetrator', 'collection', 'ashley', 'racial', 'chop', 'generals', 'drum', 'all', 'ensuing', 'pedigree', 'dispatched', 'found', 'endlessly', 'borrowing', 'composer', 'lousy', 'singing', 'compound', 'glance', 'unsympathetic', 'characterisations', 'thoughts', 'occurs', 'result', 'repression', 'harbour', 'swallowed', 'starr', 'arresting', 'imposing', 'promises', 'monroe', 'functioning', 'backbone', 'casualty', 'motive', 'caper', 'cares', 'tenth', 'milestone', 'lurks', 'su', 'overthrow', 'hurricane', 'difficulty', 'scars', 'alleged', 'awkwardly', 'fewer', 'lining', 'edges', 'confronts', 'wing', 'ricardo', 'strangely', 'tenants', 'guess', 'fragile', 'fools', 'regularly', 'thinner', 'haunts',

In [15]:
import numpy as np

In [24]:
vector_num = len(important_words)+1
print(vector_num)
hidden_state = 300
first_weight = np.random.rand(vector_num, hidden_state)
print(first_weight)
second_weight = np.random.rand(hidden_state, vector_num)

16264
[[0.01964769 0.06901696 0.8634943  ... 0.36903064 0.11562052 0.2257146 ]
 [0.995756   0.34626182 0.4242258  ... 0.60373694 0.84003104 0.17209978]
 [0.40329048 0.97021702 0.76680062 ... 0.24231872 0.88448183 0.62307787]
 ...
 [0.99070352 0.73332233 0.93195585 ... 0.46378984 0.59551553 0.4009631 ]
 [0.09705363 0.19539523 0.61754051 ... 0.05827798 0.88053349 0.38703189]
 [0.02876657 0.77737238 0.17077396 ... 0.47926978 0.53510089 0.00942821]]


In [25]:
index_dict = dict()
index_dict['NONWORD'] = 0
for i, word in enumerate(important_words):
    index_dict[word] = i+1

print(index_dict)

{'shelf': 8071, 'dungeon': 2113, 'manipulation': 5031, 'skilled': 8072, 'dread': 6119, 'liar': 14316, 'weird': 8426, 'jagger': 6120, 'sensation': 10216, 'computers': 1, 'rough': 4119, 'emphasize': 12296, 'gestures': 4110, 'state': 2, 'trainspotting': 2114, 'stalk': 15283, 'precious': 3, 'downhill': 1745, 'karate': 4111, 'mafia': 8073, 'tch': 4, 'yes': 4124, 'gadget': 12298, 'centered': 4112, 'fun': 5, 'intestines': 12246, 'halt': 4113, 'miriam': 2115, 'guise': 10917, 'hoping': 6123, 'impressively': 9188, 'drums': 8074, 'development': 1013, 'glue': 6, 'badness': 14318, 'nazi': 13193, 'fenech': 6124, 'lingers': 7, 'elisabeth': 4115, 'looked': 10215, 'reeve': 8, 'truthfully': 8075, 'broken': 9, 'drank': 8076, 'realm': 6127, 'elsewhere': 2116, 'commandos': 2117, 'wits': 8077, 'rounds': 12301, 'werewolves': 15632, 'niche': 10, 'figured': 12143, 'never': 12302, 'cold': 11, 'moriarty': 14036, 'ammo': 12, 'submit': 2118, 'stone': 4118, 'cryptic': 14319, 'btw': 12332, 'pauly': 10217, 'izzard': 

In [26]:
eye = 0
eye = np.eye(vector_num)
print(eye)
print(np.shape(eye))


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(16264, 16264)


In [35]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [36]:
# Skip-Gram
window_size = 5
for sentence in sentences:
    input = ''
    for i in range(len(sentence)):
        if not sentence[i] in index_dict:
            input = eye[0]
        else:
            input = eye[index_dict[sentence[i]]]
        hidden_layer = np.matmul(input, first_weight)
        output = np.matmul(hidden_layer, second_weight)
        print(softmax(output))
        
    break

[1.28709015e-08 2.49226661e-06 7.62716790e-06 ... 2.70265291e-06
 1.11771988e-06 2.53459779e-06]
[2.95854170e-08 2.30108482e-06 8.68468905e-05 ... 4.77668600e-08
 1.14003248e-06 1.19149477e-06]
[9.05110234e-09 3.17849870e-05 4.49184172e-05 ... 3.16296763e-08
 1.38456140e-08 2.41493328e-07]
[6.57802863e-08 2.74994940e-05 3.71383343e-06 ... 2.36739561e-06
 1.04387383e-07 1.12512532e-06]
[2.77594830e-09 6.02724284e-04 7.33737663e-06 ... 4.80882657e-07
 5.80486824e-08 9.00825027e-08]
[3.35568277e-07 1.70211235e-04 3.79344781e-06 ... 1.72049007e-07
 8.20192303e-08 1.24143090e-07]
[1.72418995e-08 1.99527794e-06 1.80206879e-06 ... 3.48627953e-07
 2.96297784e-07 1.43143192e-07]
[1.21084770e-07 1.13362156e-06 1.03594571e-04 ... 9.29915944e-08
 3.56526189e-06 1.28385236e-07]
[1.04350161e-07 2.95824143e-06 1.13390227e-05 ... 1.13179206e-07
 3.36002412e-07 4.14922707e-07]
[1.28709015e-08 2.49226661e-06 7.62716790e-06 ... 2.70265291e-06
 1.11771988e-06 2.53459779e-06]
[1.10327152e-07 6.83506533e-06

In [ ]:
with open('word_all.txt', 'w') as f:
    for word in word_set:
        print(word)
        f.write("%s\n" % word)
    f.close()

In [ ]:
a = 0
b = []
with open('word_all.txt', 'r') as f:
    while True:
        a += 1
        line = f.readline()
        b.append(line[:-1])
        if not line : break
        print(line[:-1])
    f.close()
print(a)
print(len(b))

In [ ]:
print(b[0])
print(b[1])