In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer

In [2]:
train = pd.read_csv('./word2vec-nlp-tutorial/labeledTrainData.tsv', header=0, delimiter='\t', quoting=3)
test = pd.read_csv('./word2vec-nlp-tutorial/testData.tsv', header=0, delimiter='\t', quoting=3)
unlabeled_train = pd.read_csv('./word2vec-nlp-tutorial/unlabeledTrainData.tsv', header=0, delimiter='\t', quoting=3)

print ("Read %d labeled train reviews, %d labeled test reviews, " \
 "and %d unlabeled reviews\n" % (train["review"].size,  
 test["review"].size, unlabeled_train["review"].size ))

lemmatizer = WordNetLemmatizer()

Read 25000 labeled train reviews, 25000 labeled test reviews, and 50000 unlabeled reviews



In [3]:
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Lemmatizer
    #words = [lemmatizer.lemmatize(token, "v") for token in words]
    
    # 5. Return a list of words
    return(words)

In [4]:
# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download()   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Define a function to split a review into parsed sentences
def review_to_sentences( review, tokenizer, remove_stopwords=False ):
    # Function to split a review into parsed sentences. Returns a 
    # list of sentences, where each sentence is a list of words
    #
    # 1. Use the NLTK tokenizer to split the paragraph into sentences
    raw_sentences = tokenizer.tokenize(review.strip())
    #
    # 2. Loop over each sentence
    sentences = []
    for raw_sentence in raw_sentences:
        # If a sentence is empty, skip it
        if len(raw_sentence) > 0:
            # Otherwise, call review_to_wordlist to get a list of words
            sentences.append( review_to_wordlist( raw_sentence, \
              remove_stopwords ))
    #
    # Return the list of sentences (each sentence is a list of words,
    # so this returns a list of lists
    return sentences

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [5]:
sentences = []  # Initialize an empty list of sentences

print ("Parsing sentences from training set")
for review in train["review"]:
    sentences += review_to_sentences(review, tokenizer)

print ("Parsing sentences from unlabeled set")
for review in unlabeled_train["review"]:
    sentences += review_to_sentences(review, tokenizer)

Parsing sentences from training set


C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'.'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  ' Beautiful Soup.' % markup)
C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.happierabroad.com"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup


Parsing sentences from unlabeled set


C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.archive.org/details/LovefromaStranger"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:336: UserWarning: "http://www.loosechangeguide.com/LooseChangeGuide.html"" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
C:\Users\beplu\Anaconda3\envs\virtualenv\lib\site-packages\bs4\__init__.py:273: UserWarning: "b'... ...'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.


In [6]:
print(len(sentences))

795538


In [7]:
print(sentences[1])

['maybe', 'i', 'just', 'want', 'to', 'get', 'a', 'certain', 'insight', 'into', 'this', 'guy', 'who', 'i', 'thought', 'was', 'really', 'cool', 'in', 'the', 'eighties', 'just', 'to', 'maybe', 'make', 'up', 'my', 'mind', 'whether', 'he', 'is', 'guilty', 'or', 'innocent']


In [8]:
word_set = set([])
word_dict = dict()
i = 0
for sentence in sentences:
    for word in sentence:
        if not word in word_dict:
            word_dict[word] = 1
        else:
            word_dict[word] = word_dict[word] + 1
    
    i+=1
    if i==1000:
        print(i)
        print(len(word_dict))

1000
4549


In [9]:
print(word_dict)
print(len(word_dict))

{'with': 133897, 'all': 71118, 'this': 226658, 'stuff': 3569, 'going': 12767, 'down': 11027, 'at': 70059, 'the': 1014971, 'moment': 3281, 'mj': 52, 'i': 258405, 've': 15254, 'started': 2794, 'listening': 488, 'to': 407216, 'his': 87950, 'music': 9134, 'watching': 13630, 'odd': 1686, 'documentary': 2955, 'here': 16941, 'and': 494087, 'there': 57300, 'watched': 6512, 'wiz': 20, 'moonwalker': 26, 'again': 11923, 'maybe': 7156, 'just': 53579, 'want': 11063, 'get': 27918, 'a': 491473, 'certain': 2413, 'insight': 562, 'into': 27486, 'guy': 9449, 'who': 65188, 'thought': 10396, 'was': 144148, 'really': 34922, 'cool': 3095, 'in': 282877, 'eighties': 343, 'make': 24515, 'up': 40653, 'my': 36415, 'mind': 5848, 'whether': 2391, 'he': 90071, 'is': 321694, 'guilty': 595, 'or': 54227, 'innocent': 1266, 'part': 12167, 'biography': 215, 'feature': 2262, 'film': 121221, 'which': 35835, 'remember': 4788, 'see': 34646, 'cinema': 4330, 'when': 42600, 'it': 287854, 'originally': 840, 'released': 2855, 'som

In [10]:
important_words = []
for word in word_dict.keys():
    if word_dict[word]>40:
        important_words.append(word)

In [11]:
print(important_words)
print(len(important_words))

['with', 'all', 'this', 'stuff', 'going', 'down', 'at', 'the', 'moment', 'mj', 'i', 've', 'started', 'listening', 'to', 'his', 'music', 'watching', 'odd', 'documentary', 'here', 'and', 'there', 'watched', 'again', 'maybe', 'just', 'want', 'get', 'a', 'certain', 'insight', 'into', 'guy', 'who', 'thought', 'was', 'really', 'cool', 'in', 'eighties', 'make', 'up', 'my', 'mind', 'whether', 'he', 'is', 'guilty', 'or', 'innocent', 'part', 'biography', 'feature', 'film', 'which', 'remember', 'see', 'cinema', 'when', 'it', 'originally', 'released', 'some', 'of', 'has', 'subtle', 'messages', 'about', 's', 'feeling', 'towards', 'press', 'also', 'obvious', 'message', 'drugs', 'are', 'bad', 'm', 'kay', 'visually', 'impressive', 'but', 'course', 'michael', 'jackson', 'so', 'unless', 'you', 'remotely', 'like', 'anyway', 'then', 'hate', 'find', 'boring', 'may', 'call', 'an', 'for', 'making', 'movie', 'most', 'fans', 'would', 'say', 'that', 'made', 'if', 'true', 'nice', 'him', 'actual', 'bit', 'finally

In [12]:
import numpy as np

In [13]:
vector_num = len(important_words)+1
print(vector_num)
hidden_state = 300
first_weight = np.random.rand(vector_num, hidden_state)
print(first_weight)
second_weight = np.random.rand(hidden_state, vector_num)

16264
[[6.39634687e-02 3.71321175e-01 1.04861074e-02 ... 2.79545797e-01
  7.41447539e-02 9.15931478e-01]
 [7.41459759e-04 3.92611330e-01 9.56766474e-01 ... 2.95767061e-01
  5.38125131e-01 2.46265095e-02]
 [1.05684128e-01 3.22550307e-01 4.07865980e-01 ... 6.72618553e-01
  2.68192219e-01 1.26351772e-02]
 ...
 [3.48280952e-01 5.72256442e-01 5.93337396e-01 ... 8.09341918e-01
  5.72260341e-01 5.77705256e-01]
 [2.14413419e-01 8.04295686e-01 5.60507256e-01 ... 8.51798918e-01
  2.33139675e-01 5.51009430e-01]
 [7.40916722e-01 3.76139151e-01 9.41686761e-01 ... 3.03284643e-01
  1.44895140e-01 8.19222215e-01]]


In [14]:
index_dict = dict()
index_dict['NONWORD'] = 0
for i, word in enumerate(important_words):
    index_dict[word] = i+1

print(index_dict)

{'NONWORD': 0, 'with': 1, 'all': 2, 'this': 3, 'stuff': 4, 'going': 5, 'down': 6, 'at': 7, 'the': 8, 'moment': 9, 'mj': 10, 'i': 11, 've': 12, 'started': 13, 'listening': 14, 'to': 15, 'his': 16, 'music': 17, 'watching': 18, 'odd': 19, 'documentary': 20, 'here': 21, 'and': 22, 'there': 23, 'watched': 24, 'again': 25, 'maybe': 26, 'just': 27, 'want': 28, 'get': 29, 'a': 30, 'certain': 31, 'insight': 32, 'into': 33, 'guy': 34, 'who': 35, 'thought': 36, 'was': 37, 'really': 38, 'cool': 39, 'in': 40, 'eighties': 41, 'make': 42, 'up': 43, 'my': 44, 'mind': 45, 'whether': 46, 'he': 47, 'is': 48, 'guilty': 49, 'or': 50, 'innocent': 51, 'part': 52, 'biography': 53, 'feature': 54, 'film': 55, 'which': 56, 'remember': 57, 'see': 58, 'cinema': 59, 'when': 60, 'it': 61, 'originally': 62, 'released': 63, 'some': 64, 'of': 65, 'has': 66, 'subtle': 67, 'messages': 68, 'about': 69, 's': 70, 'feeling': 71, 'towards': 72, 'press': 73, 'also': 74, 'obvious': 75, 'message': 76, 'drugs': 77, 'are': 78, 'ba

In [15]:
eye = 0
eye = np.eye(vector_num)
print(eye)
print(np.shape(eye))


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(16264, 16264)


In [16]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [29]:
# Skip-Gram
window_size = 5
for sentence in sentences:
    input = ''
    print(sentence)
    for i in range(len(sentence)):
        if not sentence[i] in index_dict:
            continue
        else:
            input = eye[index_dict[sentence[i]]]
        hidden_layer = np.matmul(input, first_weight)
        output = np.matmul(hidden_layer, second_weight)
        softmax_output = softmax(output)
        #print(softmax(output))
        target = np.zeros(vector_num)
        for j in range(int(-window_size/2), int(window_size/2)+1):
            if i+j>-1 and i+j<len(sentence) and j!=0:                
                if not sentence[i+j] in index_dict:
                    target[0] = 1
                else:
                    target[index_dict[sentence[i+j]]]=1
        #print(target)
        print(np.shape(softmax_output))
        print(np.shape(target))
        
        
        
        
    break

['with', 'all', 'this', 'stuff', 'going', 'down', 'at', 'the', 'moment', 'with', 'mj', 'i', 've', 'started', 'listening', 'to', 'his', 'music', 'watching', 'the', 'odd', 'documentary', 'here', 'and', 'there', 'watched', 'the', 'wiz', 'and', 'watched', 'moonwalker', 'again']
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)
(16264,)


In [ ]:
with open('word_all.txt', 'w') as f:
    for word in word_set:
        print(word)
        f.write("%s\n" % word)
    f.close()

In [ ]:
a = 0
b = []
with open('word_all.txt', 'r') as f:
    while True:
        a += 1
        line = f.readline()
        b.append(line[:-1])
        if not line : break
        print(line[:-1])
    f.close()
print(a)
print(len(b))

In [ ]:
print(b[0])
print(b[1])